# makefile for linux

flags = -O3 -Wall -Iode
# flags = -Wall -Iode -DDEBUG

headers := $(wildcard *.h)
source := $(patsubst %.cpp,%,$(wildcard *.cpp))

libs := -lruby

% : %.cpp ${headers}
	g++ $< -o $@ ${flags} # ${libs}

clean:
	rm -f ${source}
	rm -f *.a
